parameters:
#    facile_Adsl_admin.example.class: Facile\Adsl\AdminBundle\Example

services:
    sonata.admin.compagnia:
        class: Facile\Adsl\AdminBundle\Admin\CompagniaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Compagnia"
        arguments:
            - ~
            - Facile\Adsl\WsBundle\Entity\Compagnia
            - ~
        calls:
            - [ setTranslationDomain, [FacileAdslAdminBundle]]

    sonata.admin.tariffa:
        class: Facile\Adsl\AdminBundle\Admin\TariffaAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Tariffa"
        arguments:
            - ~
            - Facile\Adsl\WsBundle\Entity\Tariffa
            - ~
        calls:
            - [ setTranslationDomain, [FacileAdslAdminBundle]]

    sonata.admin.anagraficaLead:
        class: Facile\Adsl\AdminBundle\Admin\AnagraficaLeadAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Anagrafiche"
        arguments:
            - ~
            - Facile\Adsl\WsBundle\Entity\AnagraficaLead
            - "FacileAdslAdminBundle:AnagraficaLead"
        calls:
            - [ setTranslationDomain, [FacileAdslAdminBundle]]

    sonata.admin.sorgente:
        class: Facile\Adsl\AdminBundle\Admin\SorgenteAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Content"
              label: "Sorgente"
        arguments:
            - ~
            - Facile\Adsl\WsBundle\Entity\Sorgente
            - "FacileAdslAdminBundle:Sorgente"
        calls:
            - [ setTranslationDomain, [FacileAdslAdminBundle]]

    sonata.admin.paginaSeo:
            class: Facile\Adsl\AdminBundle\Admin\PaginaSeoAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Content"
                  label: "Pagine Seo"
            arguments:
                - ~
                - Facile\Adsl\WsBundle\Entity\PaginaSeo
                - "FacileAdslAdminBundle:PaginaSeo"
            calls:
                - [ setTranslationDomain, [FacileAdslAdminBundle]]

    sonata.admin.documento:
            class: Facile\Adsl\AdminBundle\Admin\DocumentoAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Content"
                  label: "Documento"
            arguments:
                - ~
                - Facile\Adsl\WsBundle\Entity\Documento
                - "FacileTelefoniaAdminBundle:Documento"
            calls:
                - [ setTranslationDomain, [FacileAdslAdminBundle]]