# app/config/routing.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /secure_area

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /secure_area/profile

fos_user_registration_register:
    defaults: { _controller: AcmeDemoBundle:Registration:register }
    pattern:   /secure_area/register

fos_user_registration_check_email:
    defaults: { _controller: AcmeDemoBundle:Registration:checkEmail }
    pattern:   /secure_area/register/check-email

fos_user_registration_confirm:
    defaults: { _controller: AcmeDemoBundle:Registration:checkEmail }
    pattern:   /secure_area/register/confirm/{token}

fos_user_registration_confirmed:
    defaults: { _controller: AcmeDemoBundle:Registration:confirmed }
    pattern:   /secure_area/register/confirmed

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /secure_area/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /secure_area/profile


_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin





hwi_oauth_service_redirect:
    defaults: { _controller: AcmeDemoBundle:Secured:redirectToService }
    pattern:   /secure_area/connect/{service}

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure_area/connect

hwi_oauth_connect_service:
    defaults: { _controller: AcmeDemoBundle:Secured:connectService }
    pattern:   /secure_area/connect/service/{service}

hwi_oauth_connect_registration:
    defaults: { _controller: AcmeDemoBundle:Secured:registration }
    pattern:   /secure_area/connect/registration/{key}

facebook_login:
    pattern: /secure_area/login/check-facebook