# app/config/routing.yml

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"




#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /secure_area/connect

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /secure_area/connect

#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix:   /secure_area/connect


facebook_login:
    pattern: /login/check-facebook