security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        secure_area:
            pattern: ^/

            oauth:
                failure_path: /login
                login_path: /login
                check_path: /login
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/secure_area/login/check-facebook"
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            anonymous:    true
            logout:
                path:           /logout
                target:         / #where to go after logout


    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
