_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /

_squadrareale:
    resource: "@AcmeDemoBundle/Controller/SquadraRealeController.php"
    type:     annotation
